### ISSUE TITLE
KOA Parameter and Stream Related Questions

### ISSUE THREAD

**Issue by Sobranier** [song940/kelp-logger#1]
Q1：目前的调用参数和koa默认不一样，这样造成kelp-logger其实必须要和kelp或者kelp功能类似的包一起使用

Q2：目前监听的事件是
看了一下koa-logger    https://github.com/koajs/logger/blob/master/index.js#L73
同时监听了close和finish两个事件。
按照node官方的说法close事件不是任何情况下都会触发，替换成end会好一点。但是似乎结论其实是要同时支持end和finish事件？（考虑到如果前端不仅仅读数据的话）
http://stackoverflow.com/questions/28334610/whats-the-difference-between-end-and-finish-events-in-node-streams

**Comment by lsongdev** [comment]
多谢关注 [Kelp Project](https://github.com/kelpjs), 我来解释下两个问题：
1. Kelp 的理念是尽量用简洁有效的方式实现一个高性能框架，虽然它最初只是我做的一个玩具。所以我刻意 **忘记** 所有现存的框架(你也可以理解为我只想造个轮子)，除非必要我不会添加太多复杂的东西进去，这样可以让所有人读到 [Kelp](https://github.com/kelpjs/kelp) 的代码时不会感到疑惑。另外，Koajs 是基于 Generator(or Await/Async) 的，这造成了Kelp Middleware 和 Koa 没办法一起使用。
2. 这个问题，Node.js 的[官方文档](https://nodejs.org/dist/latest-v5.x/docs/api/stream.html)上讲得比较清楚，Stream 分为两个实现，即：[ReadableStream](https://nodejs.org/dist/latest-v5.x/docs/api/stream.html#stream_class_stream_readable) 和 [WritableStream](https://nodejs.org/dist/latest-v5.x/docs/api/stream.html#stream_class_stream_writable) 。ReadableStream 结束时触发 `end`, WritableStream 结束时触发 `finish`。而 `close` 实际上是 `response socket` 的 `connection closed` 。所以你看到 koa-logger 中同时 `bind` 了 `finish` 和 `close` 事件。
